In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Cars93.csv')
df

,Unnamed: 0,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             93 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [5]:
#Removing non numeric and categorical
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [7]:
df.shape

(93, 27)

In [12]:
df.dropna(axis=0, thresh=26, inplace=True)

In [13]:
df.shape

(91, 27)

In [23]:
pd.get_dummies[df,columns = ['Manufacturer']]
#pd.get_dummies[df]

SyntaxError: invalid syntax (Temp/ipykernel_12324/2693586670.py, line 1)